### PR TITLE
Support of Fronius Smart Meter as new source

### PR DESCRIPTION
**Pull request by california444**

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
Sorry for the delay. The changes look good to me, there are only some debug leftovers.

The PR is in draft mode, does that mean you want to wait for your heat pump to be installed and then test it first?

**Comment by california444** [comment]
Hi @hendrikmuhs,
that was my plan to test it first. 
In case you want to make it available to some one else I can also make it ready for merging, just let me know...

**Comment by california444** [comment]
HI @hendrikmuhs, die Werte kann ich sehen.
Weißt du, ob noch irgendwas frei geschaltet werden muss? Trotz dauerhaftem Überschuss länger als die eingestellte "Einschaltverzögerung" schaltet sich die Lambda nicht ein...

Bildschirmfoto 2023-09-17 um 12 11 50
Bildschirmfoto 2023-09-17 um 12 12 00

**Comment by hendrikmuhs** [comment]
@california444 sorry for the late answer, but I think you figured it out already. In the screenshot it should show `-4.12` if that's what the PV  excess is, which I guess. 

So this PR is ready to go, I will look at it on the weekend.

**Comment by california444** [comment]
Works really well since a week.

**Comment by hendrikmuhs** [comment]
Thanks!

**Pull request merged**
